services:
  psql:
    image: postgres
    volumes:
      - .data/psql-data:/var/lib/postgresql/data
      - ./common/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    expose:
      - 5432
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - 17032:80
    expose:
      - 17032
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
#    volumes:
#      - .data/pgadmin/pgadmin:/var/lib/pgadmin
#      - .data/pgadmin/pgadmin4:/pgadmin4